/* eslint-disable */

// Places
export const LOAD_PLACES_SUCCESS = "LOAD_PLACES_SUCCESS";
export const CREATE_PLACE_SUCCESS = "CREATE_PLACE_SUCCESS";
export const GET_PLACE_SUCCESS = "GET_PLACE_SUCCESS";
export const UPDATE_PLACE_SUCCESS = "UPDATE_PLACE_SUCCESS";
export const DELETE_PLACE_SUCCESS = "DELETE_PLACE_SUCCESS";

//Users
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const LOG_OUT = "LOG_OUT";
